done

diff --git a/bootson b/bootson
--- a/bootson
+++ b/bootson
@@ -1,11 +1,25 @@
 #!/bin/bash
 
 # Display the instructions
-echo "This script helps you set up your WSL environment in a standard way for success."
-echo "DO NOT type 'proceed' and press Enter unless you are confident in each step you may
- leave this script running while you complete any incomplete steps just dont skip any or
-  do them out of order."
-read -p "Are you ready to proceed or do you want to quit? (proceed/exit): " user_input
+echo "This script helps you set up your WSL environment in a standard way ease of use."
+echo "DO NOT type proceed unless you are confident in each step you may leave this script
+running while you complete any incomplete steps just dont skip any or do them out of order.
+When prompted do the thing, type proceed when youv'e done the thing and press enter"
+# Prompt the user to type "proceed" or "exit"
+while true; do
+  read -p "Read the instruction above - (proceed/exit): " user_input
+  # Convert user input to lowercase for case-insensitive comparison
+  user_input_lc=$(echo "$user_input" | tr '[:upper:]' '[:lower:]')
+  if [ "$user_input_lc" == "proceed" ]; then
+    echo "Continuing..."
+    break
+  elif [ "$user_input_lc" == "exit" ]; then
+    echo "Exiting..."
+    exit 1
+  else
+    echo "Invalid input. Please type 'proceed' or 'exit'."
+  fi
+done
 
 ./apt-s3
 ./tools
